MySQL: &MYSQL
  DSN: "root:123456@tcp(mysql:3306)/engineerpro?charset=utf8mb4&parseTime=True&loc=Local"
  DefaultStringSize: 256
  DisableDatetimePrecision: true
  DontSupportRenameIndex: true
  SkipInitializeWithVersion: false
Redis: &REDIS
  Addr: redis:6379
AuthenticateAndPostConfig:
  MySQL: *MYSQL
  Redis: *REDIS
NewsfeedConfig:
  MySQL: *MYSQL
  Redis: *REDIS
WebConfig:
  AuthenticateAndPost:
    Hosts: ["aap:19001"]
  Newsfeed:
    Hosts: ["newsfeed:19002"]