CREATE SCHEMA be01_ass1;
USE be01_ass1;
CREATE TABLE PROFESSOR(
	PROF_ID INTEGER PRIMARY KEY,
    PROF_LNAME VARCHAR(50),
    PROF_FNAME VARCHAR(50)
 );
   CREATE TABLE STUDENT(
	STUD_ID INTEGER PRIMARY KEY,
    STUD_FNAME VARCHAR(50),
    STUD_LNAME VARCHAR(50),
    STUD_STREET VARCHAR(50),
    STUD_CITY VARCHAR(50),
    STUD_ZIP VARCHAR(50)
 );
 
 CREATE TABLE COURSE(
	COURSE_ID INTEGER PRIMARY KEY,
    COURSE_NAME VARCHAR(255)
 );
 
CREATE TABLE ROOM(
	ROOM_ID INTEGER PRIMARY KEY,
    ROOM_LOC VARCHAR(50),
    ROOM_CAP VARCHAR(50)
);

CREATE TABLE CLASS(
	CLASS_ID INTEGER PRIMARY KEY,
    CLASS_NAME VARCHAR(255),
	PROF_ID INTEGER,
    COURSE_ID INTEGER,
    ROOM_ID INTEGER,
    FOREIGN KEY (PROF_ID) REFERENCES PROFESSOR(PROF_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID)
);
CREATE TABLE ENROLL(
	STUD_ID INTEGER,
    CLASS_ID INTEGER,
	FOREIGN KEY (STUD_ID) REFERENCES STUDENT(STUD_ID),
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
    GRADE VARCHAR(3),
    PRIMARY KEY(STUD_ID, CLASS_ID)
);
CREATE TABLE ClassRoom(
	CLASS_ID INTEGER,
    ROOM_ID INTEGER,
    FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID),
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
    PRIMARY KEY (CLASS_ID, ROOM_ID)
)